version: "3.9"

services:
  monitor:
    image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
    container_name: bs_monitor
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env          # сюда кладём TG_TOKEN и TG_CHAT_ID
    command: ["python", "monitor.py"]
    restart: unless-stopped
